options:
  active:
    type: boolean
    default: true
    description: If true, enable jobs that may change the database.
  domain_librarian:
    type: string
    description: Domain name for this instance's librarian service.
    default: "launchpadlibrarian.test"
  domain_librarian_aliases:
    type: string
    default: "[]"
    description: >
      A YAML-encoded list of aliases for the librarian's primary domain.
  haproxy_server_options:
    type: string
    description: Options to add to HAProxy "server" lines.
    default: check inter 5000 rise 2 fall 5 maxconn 16
  haproxy_service_options_download:
    type: string
    description: HAProxy options for download services.
    default: |
      - mode http
      - option httplog
      - option httpchk HEAD / HTTP/1.0
      - option forwardfor
      - balance leastconn
  haproxy_service_options_upload:
    type: string
    description: HAProxy options for upload services.
    default: |
      - mode tcp
      - option tcplog
      - option httpchk HEAD / HTTP/1.0
      - option forwardfor
      - balance leastconn
      - timeout client 600000
      - timeout server 600000
  old_os_auth_url:
    type: string
    description: >
      OpenStack authentication URL for a previous Swift instance that we're
      migrating away from, but should still read from if necessary.
    default:
  old_os_auth_version:
    type: string
    description: >
      OpenStack authentication protocol version for a previous Swift
      instance that we're migrating away from, but should still read from if
      necessary.
    default: "2.0"
  old_os_password:
    type: string
    description: >
      OpenStack password for a previous Swift instance that we're migrating
      away from, but should still read from if necessary.
    default:
  old_os_tenant_name:
    type: string
    description: >
      OpenStack tenant name for a previous Swift instance that we're
      migrating away from, but should still read from if necessary.
    default:
  old_os_username:
    type: string
    description: >
      OpenStack username for a previous Swift instance that we're migrating
      away from, but should still read from if necessary.
    default:
  os_auth_url:
    type: string
    description: OpenStack authentication URL.
    default:
  os_auth_version:
    type: string
    description: OpenStack authentication protocol version.
    default: "2.0"
  os_password:
    type: string
    description: OpenStack password.
    default:
  os_tenant_name:
    type: string
    description: OpenStack tenant name.
    default:
  os_username:
    type: string
    description: OpenStack username.
    default:
  port_download_base:
    type: int
    description: Base port number for public download workers.
    default: 8000
  port_restricted_download_base:
    type: int
    description: Base port number for restricted download workers.
    default: 8005
  port_restricted_upload_base:
    type: int
    description: Base port number for restricted upload workers.
    default: 9095
  port_upload_base:
    type: int
    description: Base port number for public upload workers.
    default: 9090
  ssl_chain_required:
    type: boolean
    description: >
      Whether an intermediate certificate chain is needed for this service.
      In development, we use self-signed certificates which don't have a
      certificate chain; but in real deployments, we need to send a
      certificate chain.
    default: false
  backfill_sha512_workers:
    type: int
    description: Number of parallel download workers for librarian-backfill-sha512.
    default: 2
  swift_feed_workers:
    type: int
    description: Number of librarian-feed-swift workers to run in parallel.
    default: 1
  swift_timeout:
    type: int
    description: Time in seconds to wait for a response from Swift.
    default: 15
  upstream_host:
    type: string
    description: Host name for the upstream librarian, if any.
    default:
  upstream_port:
    type: int
    description: Port for the upstream librarian, if any.
    default: 80
  webmaster_email:
    type: string
    description: Email address to include in Apache virtual host configuration.
    default: "webmaster@launchpad.test"
  workers:
    type: int
    description: >
      Number of librarian worker processes.  If set, each worker will listen
      on consecutive ports starting from each of `port_download_base`,
      `port_restricted_download_base`, `port_restricted_upload_base`, and
      `port_upload_base`, so make sure there is enough space between those.
    default: 1
